// Auto-generated by `npx boneyard-js scan` — do not edit
import { registerBones } from 'boneyard-js/native'

import _specialOffer_down from './specialOffer-down.bones.json'
import _SpecialOffers from './SpecialOffers.bones.json'
import _Special_Offer_Card from './Special-Offer-Card.bones.json'
import _special_event from './special-event.bones.json'
import _sponsor_card from './sponsor-card.bones.json'
import _offerCard from './offerCard.bones.json'
import _circularChip from './circularChip.bones.json'
import _Product_card from './Product-card.bones.json'
import _MasonryList from './MasonryList.bones.json'
import _Cart from "./Cart.bones.json"
import _Profile_card from "./profile-card.bones.json"
import _Product_Details_Delivery from "./product-details-delivery.json"
import _Product_Details_Image from "./product-details-image.json"
import _Product_Details_Info from "./product-details-info.json"
import _Product_Details_SizeCard from "./product-details-sizeCard.json"

registerBones({
  "specialOffer-down": _specialOffer_down,
  "SpecialOffers": _SpecialOffers,
  "Special-Offer-Card": _Special_Offer_Card,
  "special-event": _special_event,
  "sponsor-card": _sponsor_card,
  "offerCard": _offerCard,
  "circularChip": _circularChip,
  "Product-card": _Product_card,
  "MasonryList": _MasonryList,
  "Cart": _Cart,
  "profile-card": _Profile_card,
  "product-details-delivery": _Product_Details_Delivery,
  "product-details-image": _Product_Details_Image,
  "product-details-info": _Product_Details_Info,
  "product-details-sizeCard": _Product_Details_SizeCard
})
